[global]
log_level = "info"
redis_url = "redis://redis:6379"

[filer]
port = 8888
grpc_port = 8889
metrics_port = 8900
net_port = 9334
data_dir = "/data/filer"
shard_count = 2
raft_id = 3
master_addresses = ["172.20.0.11:9333", "172.20.0.12:9333", "172.20.0.13:9333"]
master_net_port = 9334
