[global]
log_level = "info"
redis_url = "redis://redis:6379"

[volume]
grpc_port = 8080
http_port = 8091
net_port = 8901
data_dir = "/data"
node_id = "volume-server-1"
master_addresses = ["172.20.0.11:9333"]
master_net_port = 9334
max_volume_size = 107374182400   # 100GB
initial_volume_count = 2
advertise_addr = "172.20.0.21"
