mod admin;
mod assign;
mod cert;
mod cluster_add;
mod cluster_remove;
mod cluster_status;
mod cluster_transfer;
mod collection;
mod compact;
mod config_gen;
mod conflicts;
mod debug;
mod filer_stats;
mod fsck;
mod fuse_stats;
mod grow;
mod heartbeat;
mod kv;
mod lookup;
mod manage;
mod mount;
mod read;
mod status;
mod topology;
mod volume_list;
mod write;

pub use admin::{admin, AdminSubcommand};
pub use assign::{assign, AssignArgs};
pub use cert::{cert, CertSubcommand};
pub use cluster_add::{cluster_add, ClusterAddArgs};
pub use cluster_remove::{cluster_remove, ClusterRemoveArgs};
pub use cluster_status::{cluster_status, ClusterStatusArgs};
pub use cluster_transfer::{cluster_transfer, ClusterTransferArgs};
pub use collection::{collection, CollectionArgs};
pub use compact::{compact, CompactArgs};
pub use config_gen::{config_gen, ConfigGenArgs};
pub use conflicts::{conflicts, ConflictsArgs};
pub use debug::{debug, DebugArgs};
pub use filer_stats::{filer_stats, FilerStatsArgs};
pub use fsck::{fsck, FsckArgs};
pub use fuse_stats::{fuse_stats, FuseStatsArgs};
pub use grow::{grow, GrowArgs};
pub use heartbeat::{heartbeat, HeartbeatArgs};
pub use kv::{kv, KvArgs};
pub use lookup::{lookup, LookupArgs};
pub use manage::{manage, ManageArgs};
pub use mount::{mount, MountArgs};
pub use read::{read, ReadArgs};
pub use status::{status, StatusArgs};
pub use topology::{topology, TopologyArgs};
pub use volume_list::{volume_list, VolumeListArgs};
pub use write::{write, WriteArgs};

use powerfs_common::error::Result;

/// Common result type for commands
pub type CommandResult = Result<()>;
